// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyaosogliekotdebnzpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YW9zb2dsaWVrb3RkZWJuenByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzUwNTMsImV4cCI6MjA2OTk1MTA1M30.97zGlQ9hcPqM-pRn0qIUVjvrvpwi7DBWmTgXx_r6NJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});